### ISSUE TITLE
Mobile console extensions

### ISSUE THREAD

**Issue by kazhamiakin** [smartcommunitylab/smartcampus.gamification#65] opened 2016-03-22 11:18 UTC
1. Add the following info to the console (as separate contents)
- privacy and data treatment
- information for real prizes
- game rules
These infos should be visible in menu (as separate pages) and linked in the registration page (and opened separately)

2. Add "?" icon for challenge with detailed description popup (una guida dei criteri di assegnazione dei punteggi forse andrà inserito nella console di presentazione)

3. Social sharing of my data (include facebook, g+, twitter).

**Comment by regolo85** [comment] 2016-03-24 16:26
Corrected mobile console with changes required in issue. To close the issue is necessary to add text in privacy, rules and prizes pages, to insert information of challenge point in challenges page and to model the sharing text in user data page.
Added some new features like:

- recommendation user nickname check and post to gamefication server at first time user access;
- new badges render (to be ended with new icons);
- challenge page graphics update (to be validated);

**Closed** 2016-03-30 15:06 UTC
Labels: story
